/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package texteditor;

import java.awt.Color;
import java.awt.GraphicsEnvironment;
import java.awt.HeadlessException;
import java.io.*;
/*import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Reader;*/
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.nio.charset.StandardCharsets;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.AttributeSet;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Element;
import javax.swing.text.Highlighter;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author osman.mejia
 */
public class Iditor extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Iditor() {
        initComponents();
        jTextArea1.setEnabled(false);
        // BtnNegrita.setEnabled(false);
        doc = tp_texto.getStyledDocument();
        estilo = tp_texto.addStyle("miEstilo", null);

        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_font.getModel();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String fontNames[] = ge.getAvailableFontFamilyNames();
        for (int i = 0; i < fontNames.length; i++) {
            modelo.addElement(fontNames[i]);
        }
        cb_font.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tp_texto = new javax.swing.JTextPane();
        jToolBar1 = new javax.swing.JToolBar();
        cb_font = new javax.swing.JComboBox<>();
        cb_tamaño = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        BtnNegrita = new javax.swing.JButton();
        BtnCursiva = new javax.swing.JButton();
        BtnSubrayado = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        BtnColorSubrayado = new javax.swing.JButton();
        BtnColorText = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        BtnGuardar = new javax.swing.JButton();
        BtnAbrir = new javax.swing.JButton();
        BtnUrl = new javax.swing.JButton();
        txtURL = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editor Texto");

        tp_texto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(tp_texto);

        jToolBar1.setRollover(true);

        cb_font.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_fontItemStateChanged(evt);
            }
        });
        jToolBar1.add(cb_font);

        cb_tamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "18", "24", "36", "48", "60", "72" }));
        cb_tamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tamañoActionPerformed(evt);
            }
        });
        jToolBar1.add(cb_tamaño);
        jToolBar1.add(jSeparator2);

        BtnNegrita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditor/Imagenes/negrita.png"))); // NOI18N
        BtnNegrita.setToolTipText("");
        BtnNegrita.setFocusable(false);
        BtnNegrita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnNegrita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnNegrita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnNegritaMouseClicked(evt);
            }
        });
        BtnNegrita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNegritaActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnNegrita);

        BtnCursiva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditor/Imagenes/Cursiva.png"))); // NOI18N
        BtnCursiva.setFocusable(false);
        BtnCursiva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCursiva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnCursiva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCursivaMouseClicked(evt);
            }
        });
        jToolBar1.add(BtnCursiva);

        BtnSubrayado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditor/Imagenes/Subrayado.png"))); // NOI18N
        BtnSubrayado.setFocusable(false);
        BtnSubrayado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSubrayado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnSubrayado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSubrayadoMouseClicked(evt);
            }
        });
        BtnSubrayado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubrayadoActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnSubrayado);
        jToolBar1.add(jSeparator1);

        BtnColorSubrayado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditor/Imagenes/fondo.png"))); // NOI18N
        BtnColorSubrayado.setFocusable(false);
        BtnColorSubrayado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnColorSubrayado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnColorSubrayado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnColorSubrayadoMouseClicked(evt);
            }
        });
        BtnColorSubrayado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnColorSubrayadoActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnColorSubrayado);

        BtnColorText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditor/Imagenes/letra.png"))); // NOI18N
        BtnColorText.setFocusable(false);
        BtnColorText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnColorText.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnColorText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnColorTextMouseClicked(evt);
            }
        });
        BtnColorText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnColorTextActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnColorText);

        jToolBar2.setRollover(true);

        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditor/Imagenes/guardar.png"))); // NOI18N
        BtnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnGuardarMouseClicked(evt);
            }
        });
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        jToolBar2.add(BtnGuardar);

        BtnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditor/Imagenes/abrir.png"))); // NOI18N
        BtnAbrir.setFocusable(false);
        BtnAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAbrirMouseClicked(evt);
            }
        });
        BtnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAbrirActionPerformed(evt);
            }
        });
        jToolBar2.add(BtnAbrir);

        BtnUrl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditor/Imagenes/url.png"))); // NOI18N
        BtnUrl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnUrl.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUrlActionPerformed(evt);
            }
        });
        jToolBar2.add(BtnUrl);
        jToolBar2.add(txtURL);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnColorSubrayadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnColorSubrayadoMouseClicked
        // TODO add your handling code here:
        try {

            StyleConstants.setBackground(estilo,
                    JColorChooser.showDialog(this,
                            "Seleccione Color", Color.yellow)
            );

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (HeadlessException ex) {
        }
    }//GEN-LAST:event_BtnColorSubrayadoMouseClicked

    private void BtnColorTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnColorTextMouseClicked
        // TODO add your handling code here:
        try {

            StyleConstants.setForeground(estilo,
                    JColorChooser.showDialog(this,
                            "Seleccione Color", Color.red)
            );

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (HeadlessException ex) {
        }
    }//GEN-LAST:event_BtnColorTextMouseClicked

    private void BtnNegritaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNegritaMouseClicked
        // TODO add your handling code here:
        try {
            StyleConstants.setBold(estilo, true);

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_BtnNegritaMouseClicked

    private void BtnCursivaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCursivaMouseClicked
        // TODO add your handling code here:
        try {
            StyleConstants.setItalic(estilo, true);

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_BtnCursivaMouseClicked

    private void BtnSubrayadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSubrayadoMouseClicked
        // TODO add your handling code here:
        try {
            StyleConstants.setUnderline(estilo, true);

            doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                    tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                    tp_texto.getStyle("miEstilo"),
                    true);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_BtnSubrayadoMouseClicked

    private void cb_tamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tamañoActionPerformed
        // TODO add your handling code here:
        StyleConstants.setFontSize(estilo, Integer.parseInt(cb_tamaño.getSelectedItem().toString()));
        doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                tp_texto.getStyle("miEstilo"),
                true);
    }//GEN-LAST:event_cb_tamañoActionPerformed

    private void cb_fontItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_fontItemStateChanged
        // TODO add your handling code here:
        StyleConstants.setFontFamily(estilo, cb_font.getSelectedItem().toString());
        //StyleConstants.setFontSize(estilo, Integer.parseInt(cb_tamaño.getSelectedItem().toString()));
        doc.setCharacterAttributes(tp_texto.getSelectionStart(),
                tp_texto.getSelectionEnd() - tp_texto.getSelectionStart(),
                tp_texto.getStyle("miEstilo"),
                true);
    }//GEN-LAST:event_cb_fontItemStateChanged

    private void BtnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGuardarMouseClicked
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro
                = new FileNameExtensionFilter(
                        "Documentos", "txt");
        jfc.setFileFilter(filtro);
        int seleccion = jfc.showSaveDialog(this);

        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {

                File fichero = null;
                if (jfc.getFileFilter().getDescription().equals(
                        "Documentos")) {
                    fichero
                            = new File(jfc.getSelectedFile().getPath() + ".txt");
                } else {
                    fichero = jfc.getSelectedFile();
                }

                fw = new FileOutputStream(fichero);
                bw = new ObjectOutputStream(fw);
                Documento d = new Documento(tp_texto, doc, estilo);
                bw.writeObject(d);
                bw.flush();

                JOptionPane.showMessageDialog(this,
                        "Archivo guardado exitosamente");

            } catch (Exception e) {
                e.printStackTrace();
            }

        }//fin IF
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }

    }//GEN-LAST:event_BtnGuardarMouseClicked

    private void BtnAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAbrirMouseClicked
        // TODO add your handling code here:
        File fichero = null;
        FileInputStream entrada = null;
        ObjectInputStream objeto = null;
        try {
            JFileChooser jfc = new JFileChooser();
            FileNameExtensionFilter filtro
                    = new FileNameExtensionFilter(
                            "Documentos", "txt");
            jfc.setFileFilter(filtro);
            int seleccion = jfc.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = jfc.getSelectedFile();
                entrada
                        = new FileInputStream(fichero);
                objeto
                        = new ObjectInputStream(entrada);
                tp_texto.setText("");
                Documento temp = (Documento) objeto.readObject();
                tp_texto.setText(((Documento) temp).getPanel().getText());
                tp_texto.setDocument(((Documento) temp).getDoc());

            } //fin if

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            objeto.close();
            entrada.close();
        } catch (IOException ex) {
        }

    }//GEN-LAST:event_BtnAbrirMouseClicked


    private void BtnColorSubrayadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnColorSubrayadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnColorSubrayadoActionPerformed

    private void BtnSubrayadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubrayadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSubrayadoActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnNegritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNegritaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNegritaActionPerformed

    private void BtnColorTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnColorTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnColorTextActionPerformed

    private void BtnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAbrirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAbrirActionPerformed

    private void BtnUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUrlActionPerformed
//        tp_texto.setEnabled(false);

        String DIRECCION = txtURL.getText();
        String codificacion = StandardCharsets.ISO_8859_1.toString();
        File f;
        //declaracion para guardar
        FileWriter w;
        BufferedWriter bw;
        PrintWriter wr;
        //variables para la lectura
        FileReader fr;
        BufferedReader br;
        try {
            //creamos el arhico lo guardamos para luego buscarlo
            f = new File("prueba.txt");
            //estoy itanciando los valores para guardar
            w = new FileWriter(f);
            bw = new BufferedWriter(w);
            wr = new PrintWriter(bw);

            //declarar lecturas
            fr = new FileReader(f);
            br = new BufferedReader(fr);
            String linea;

            //variables para la url
            URL url = new URL(DIRECCION);
            URLConnection conexion = url.openConnection();

            // Determinación del tipo de codificación:
            String tipoContenido = conexion.getContentType();
            int indiceInicioCodificacion = tipoContenido.indexOf("charset=");

            if (indiceInicioCodificacion != -1) {
                codificacion = tipoContenido.substring(indiceInicioCodificacion + 8);
            }

            // Lectura del contenido del documento HTML:
            InputStream is = new BufferedInputStream(conexion.getInputStream());
            Reader r = new InputStreamReader(is, codificacion);
            int caracter;

            while ((caracter = r.read()) != -1) {
                wr.write((char) caracter);
                //wr.write("\n");
                //System.out.print((char) caracter);
            }

            while ((linea = br.readLine()) != null) {
                jTextArea1.append(linea);
                linea = br.readLine();
            }

            tp_texto.setText(jTextArea1.getText());
            wr.close();
            bw.close();
            br.close();
            fr.close();
        } catch (MalformedURLException e) {
            System.err.println("La URL está mal formada.");

        } catch (IOException e) {
            System.err.println("Error de entrada/salida: " + e.getMessage());
        }


    }//GEN-LAST:event_BtnUrlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAbrir;
    private javax.swing.JButton BtnColorSubrayado;
    private javax.swing.JButton BtnColorText;
    private javax.swing.JButton BtnCursiva;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnNegrita;
    private javax.swing.JButton BtnSubrayado;
    private javax.swing.JButton BtnUrl;
    private javax.swing.JComboBox<String> cb_font;
    private javax.swing.JComboBox<String> cb_tamaño;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTextPane tp_texto;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables

    StyledDocument doc;
    Style estilo;

}
